### ISSUE TITLE
Tracking Pixel URL is included in the hit counts on articles

### ISSUE THREAD

**Issue by benlk** [INN/republication-tracker-tool#80]
One site reported massively distorted hit counts within the article view, where the hit counter for the sharing URL was orders of magnitude higher than the hit counts for third-party URLs where the tracking image was embedded.

- [ ] is this a problem with the reporting code that runs when the pixel URL is hit?
- [ ] is this a problem with the table that displays results?
- [ ] is this hit reflected in GA numbers? (see #79)
